### PR TITLE
Update spline to be slightly more robust

### PR DESCRIPTION
**Pull request by christinahedges**
Extracted out of #54, this is just a slightly more robust version of this part of the code.

### CODE REVIEW

**Comment by jorgemarpa** [comment]
CI is failing because of an error installing `pyvo v1.1`. It seems that the new version v1.4 might fix the issue, but this requires Astropy v5.x, which only requires Python < 3.8

**Review by christinahedges — COMMENTED** [review]
This LGTM!

**Comment by jorgemarpa** [comment]
@christinahedges shall we merge this then?

**Comment by jorgemarpa** [comment]
I simplify the code in `make_cartesian_A` and `spline1d` to avoid repeated code, the behavior is the same. 

Merging...

**Pull request merged**
